# Generated by Django 4.2.7 on 2025-02-13 14:37

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the dish", max_length=215),
                ),
                ("description", models.TextField(help_text="Description of the dish")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price of the dish", max_digits=6
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "username",
                    models.CharField(
                        default=bookings.models.generate_unique_username,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("password1", models.CharField(max_length=30)),
                ("password2", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.IntegerField(unique=True)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person booking (if not logged in)",
                        max_length=100,
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the person booking (if not logged in)",
                        max_length=254,
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(help_text="Format: YYYY-MM-DD HH:MM"),
                ),
                ("number_of_guests", models.IntegerField(help_text="Number of guests")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "is_cancelled",
                    models.BooleanField(
                        default=False, help_text="Check if booking is cancelled"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookings.table"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
