# Generated by Django 4.2.18 on 2025-02-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="pårice",
            new_name="price",
        ),
    ]
