# Generated by Django 4.2.7 on 2025-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.CharField(
                blank=True, help_text="Category of the dish", max_length=50, null=True
            ),
        ),
    ]
