# Generated by Django 4.2.7 on 2025-02-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_menu_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("table", "date_time")},
        ),
    ]
